services:
  aigov-insight-page:
    build:
      context: .
      args:
        ASTRO_BASE: ${ASTRO_BASE:-/}
    image: aigov-insight-page:v0.3.0
    container_name: aigov-insight-page
    ports:
      - 8080:8080
