site:
  name: AIGov-Insight
  site: 'https://dreamheart09.github.io'

  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false

metadata:
  title:
    default: 'AIGov-Insight - 全球领先的AI自主智能体全链路可观测平台'
    template: '%s — AIGov-Insight | 恒安嘉新'
  description: 'Eversec AIGov-Insight 专为 LLM/Agent/MCP/RAG/OpenClaw 打造，让 AI 的每一次"思考"与"行动"全程透明、可溯、可控。AI世界的行车记录仪。'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'AIGov-Insight'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@eversec'
    site: '@eversec'
    cardType: summary_large_image

i18n:
  language: zh
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
